# Generated by Django 5.2.1 on 2025-05-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_date'),
        ('core', '0004_application_updates'),
    ]

    operations = [
    ]
