# Generated by Django 5.2.1 on 2025-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organizerprofile_avatar_talentprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='faculty',
        ),
        migrations.AddField(
            model_name='event',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.faculty', verbose_name='Доступные факультеты'),
        ),
        migrations.AddField(
            model_name='event',
            name='faculty_restriction',
            field=models.BooleanField(default=False, verbose_name='Ограничение по факультетам'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_skills',
            field=models.TextField(),
        ),
    ]
