# Generated by Django 5.2.1 on 2025-05-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_event_required_skills_event_required_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='organizerprofile',
            options={'verbose_name': 'Профиль организатора', 'verbose_name_plural': 'Профили организаторов'},
        ),
    ]
